main: me.resurrectajax.nationslegacy.main.Nations
name: Nations-Legacy
version: 1.0.1
author: ResurrectAjax
description: Create nations, claim land, wage war!
api-version: 1.19
depend: [PlaceholderAPI]

commands:
  Nations:
    description: run a Nations command
    usage: /<command>
    aliases: n