main: main.Main
name: Nations-Legacy
version: 1.0.0
author: ResurrectAjax
description: Nations
api-version: 1.19
depend: [PlaceholderAPI]

commands:
  Nations:
    description: run a Nations command
    usage: /<command>
    aliases: n